### PR TITLE
Sprint 1/issue 1#main login design

### LINKED ISSUE #1: Main Login Design
## DESCRIPTION

We will start with the layout of the application.

## DESIGN
image

### PR DESCRIPTION
**Pull request by Alfredo20164920**
# Description

> Create all the styles and structure of main login screen, and download the main icon

- Implement `Pressable` component to show the buttons
- Modify the design to do modern and simple

## Screenshots

image

### CODE REVIEW

**Review by montsegv-2 — APPROVED** [review]
LGTM! 💯

**Review by Lizzflores — APPROVED** [review]
LGTM!

**Review by Antonio3veces3 — APPROVED** [review]
Well Done!

**Review by Eduardoespl — APPROVED** [review]
LGTM 🚀

**Pull request merged**
